### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by nestordemeure** [rust-photogrammetry/hnsw#10]
The readme currently features a lot of benchmark pictures but no code example.

Adding a separate benchmark file (linked in the readme) and scaling down to one picture plus one or two typical use case examples in the readme would make the library easier to use.

**Comment by vadixidav** [comment]
I definitely agree. I will probably work on making the README more useful later today. I will split the benchmarks into their own markdown file.

**Comment by vadixidav** [comment]
Going to do this now. Ended up being more busy yesterday than expected.

**Comment by vadixidav** [comment]
I ended up not only improving the README, but I also just made floats much faster due to SIMD impls and also added some fixed size floating point impls as well for completeness and ease-of-use. That makes the examples tidy.
